name: CI
on:
  push:
    branches: [main, develop]
    paths: ["src/**", "tests/**", ".github/workflows/ci.yml"]
  pull_request:
    branches: [main, develop]
    paths: ["src/**", "tests/**", ".github/workflows/ci.yml"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | RYE_INSTALL_OPTION="--yes" bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH

      - name: Setup Python ${{matrix.python-version}} & Dependencies
        run: |
          rye pin ${{ matrix.python-version }}
          rye sync --update-all --all-features

      - name: Install optional dependent tool (infernal) on Ubuntu
        run: |
          sudo apt update -y
          sudo apt install -y infernal
        if: ${{ matrix.os=='ubuntu-latest'}}

      - name: Install optional dependent tool (infernal) on MacOS
        run: |
          brew tap brewsci/bio
          brew install infernal
        if: ${{ matrix.os=='macos-latest'}}

      - name: Run ruff lint check
        run: rye run ruff check --diff

      - name: Run ruff format check
        run: rye run ruff format --check --diff

      - name: Run pytest
        run: rye run pytest
